CPP = g++
CPPFLAGS = -std=c++17 -Wall -Werror -pedantic -o

mytree:
	$(CPP) $(CPPFLAGS) mytree.x mytree.cpp

mytime:
	$(CPP) $(CPPFLAGS) mytime.x mytime.cpp

mymtimes:
	$(CPP) $(CPPFLAGS) mymtimes.x mymtimes.cpp

clean:
	rm -v *.x
